
package es.udc.mashup.productprovider.internal.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "InternalProviderService", targetNamespace = "http://internalprovider.mashup.udc.es/", wsdlLocation = "file:/home/raicar/workspace/mashup/internalprovider/target/jaxws/wsgen/wsdl/InternalProviderService.wsdl")
public class InternalProviderService
    extends Service
{

    private final static URL INTERNALPROVIDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.udc.mashup.productprovider.internal.wsdl.InternalProviderService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.udc.mashup.productprovider.internal.wsdl.InternalProviderService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/raicar/workspace/mashup/internalprovider/target/jaxws/wsgen/wsdl/InternalProviderService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/raicar/workspace/mashup/internalprovider/target/jaxws/wsgen/wsdl/InternalProviderService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTERNALPROVIDERSERVICE_WSDL_LOCATION = url;
    }

    public InternalProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InternalProviderService() {
        super(INTERNALPROVIDERSERVICE_WSDL_LOCATION, new QName("http://internalprovider.mashup.udc.es/", "InternalProviderService"));
    }

    /**
     * 
     * @return
     *     returns InternalProvider
     */
    @WebEndpoint(name = "InternalProviderPort")
    public InternalProvider getInternalProviderPort() {
        return super.getPort(new QName("http://internalprovider.mashup.udc.es/", "InternalProviderPort"), InternalProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InternalProvider
     */
    @WebEndpoint(name = "InternalProviderPort")
    public InternalProvider getInternalProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://internalprovider.mashup.udc.es/", "InternalProviderPort"), InternalProvider.class, features);
    }

}
