
package es.udc.mashup.productprovider.internal.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InternalProvider", targetNamespace = "http://internalprovider.mashup.udc.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InternalProvider {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<es.udc.mashup.productprovider.internal.wsdl.ProductWTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findProductsByDate", targetNamespace = "http://internalprovider.mashup.udc.es/", className = "es.udc.mashup.productprovider.internal.wsdl.FindProductsByDate")
    @ResponseWrapper(localName = "findProductsByDateResponse", targetNamespace = "http://internalprovider.mashup.udc.es/", className = "es.udc.mashup.productprovider.internal.wsdl.FindProductsByDateResponse")
    public List<ProductWTO> findProductsByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<es.udc.mashup.productprovider.internal.wsdl.ProductWTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findProducts", targetNamespace = "http://internalprovider.mashup.udc.es/", className = "es.udc.mashup.productprovider.internal.wsdl.FindProducts")
    @ResponseWrapper(localName = "findProductsResponse", targetNamespace = "http://internalprovider.mashup.udc.es/", className = "es.udc.mashup.productprovider.internal.wsdl.FindProductsResponse")
    public List<ProductWTO> findProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3);

}
